version: '3.8'

services:
  smart_shower_meter:
    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - "80"

    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.services.smart_shower_meter.loadbalancer.server.port=80

networks:
  coolify:
    external: true
