version: '3.8'

services:
  smart_shower_meter:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    expose:
      - "80"

    labels:
      - traefik.enable=true
      - traefik.http.services.smart_shower_meter.loadbalancer.server.port=80
